name: Discord Notification

on: [push]

jobs:
  discord_notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Send notification to Discord
      uses: Ilshidur/action-discord@0.3.2
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: 'A new commit has been pushed to the repository "$${{ github.repository }}" by "$${{ github.actor }}". Check it out at: $${{ github.event.compare }}.'
