name: Discord Notification

on: [push]

jobs:
  discord_notify:
    runs-on: ubuntu-latest
    steps:
      name: Send notification to Discord
      uses: Ilshidur/action-discord@0.3.2
      with:
        args: "A new commit has been pushed to the repository. Check it out at: ${{ github.event.compare }}."
        channel_id: 1089899598325223524
        token: ${{ secrets.DISCORD_BOT_TOKEN }}
